# Generated by Django 4.1.5 on 2023-08-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_logincredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredentials',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
